# Generated by Django 3.0.8 on 2020-07-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0002_auto_20200724_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password2',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='password2',
            name='site',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='password2',
            name='userps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
