# Generated by Django 3.0.8 on 2020-10-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20200724_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassWord2',
        ),
    ]
